services:
  app:
    build: .
    container_name: twiga_app_c
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/src/app  # Mount the app directory to /src/app in the container
      - ./db:/src/db  # Mount the db directory to /src/db in the container
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload