version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: docker/dev/db/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: docker/dev/app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  db:
