[project]
name = "twiga"
version = "0.1.0"
description = "A WhatsApp chatbot for teachers" 
authors = ["Victor Oldensand <victormag24@gmail.com>"]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
