[project]
name = "twiga"
version = "0.1.0"
description = "A WhatsApp chatbot for Tanzanian Teachers"
readme = "README.md"
authors = ["Victor Oldensand <victormag24@gmail.com>"]
requires-python = ">=3.12"
license = "MIT"
dependencies = [
    "chromadb>=0.5.13",
    "colorlog>=6.8.2",
    "fastapi>=0.115.0",
    "groq>=0.11.0",
    "httpx>=0.27.2",
    "openai>=1.51.2",
    "prisma>=0.15.0",
    "pydantic-settings>=2.5.2",
    "tiktoken>=0.8.0",
]
