[project]
name = "twiga"
version = "0.1.0"
description = "A WhatsApp chatbot for Tanzanian Teachers"
readme = "README.md"
authors = ["Victor Oldensand <victormag24@gmail.com>"]
requires-python = ">=3.12"
license = "MIT"
dependencies = [
    "alembic>=1.13.3",
    "asyncpg>=0.29.0",
    "chromadb>=0.5.13",
    "colorlog>=6.8.2",
    "fastapi>=0.115.0",
    "greenlet>=3.1.1",
    "groq>=0.11.0",
    "httpx>=0.27.2",
    "openai>=1.51.2",
    "pgvector>=0.3.5",
    "psycopg2-binary>=2.9.10",
    "pydantic-settings>=2.5.2",
    "sqlmodel>=0.0.22",
    "tiktoken>=0.8.0",
    "together>=1.3.3",
]
