[project]
name = "twiga"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = ["Victor Oldensand <victormag24@gmail.com>"]
requires-python = ">=3.12"
license = "MIT"
dependencies = [
    "colorlog>=6.8.2",
    "fastapi>=0.115.0",
]
